#!/bin/sh
# ZeroTier: убрать публичную сеть Earth из примера конфигурации и создать
# зону межсетевого экрана для интерфейсов zt* с доступом в LAN и из LAN.

uci -q get zerotier.sample_config >/dev/null && \
	uci -q del_list zerotier.sample_config.join=8056c2e21c000001 && \
	uci -q commit zerotier

uci -q get firewall.zerotier >/dev/null || {
	uci -q batch <<-EOT
		set firewall.zerotier=zone
		set firewall.zerotier.name=zerotier
		set firewall.zerotier.input=ACCEPT
		set firewall.zerotier.output=ACCEPT
		set firewall.zerotier.forward=ACCEPT
		set firewall.zerotier.masq=1
		add_list firewall.zerotier.device=zt+
		set firewall.zerotier_lan=forwarding
		set firewall.zerotier_lan.src=zerotier
		set firewall.zerotier_lan.dest=lan
		set firewall.lan_zerotier=forwarding
		set firewall.lan_zerotier.src=lan
		set firewall.lan_zerotier.dest=zerotier
		commit firewall
	EOT
}
exit 0
