#!/bin/sh
# Светодиод WAN пересчитывается при подъёме/падении любого интерфейса:
# маршрут по умолчанию может дать wan, wan6, L2TP, VPN...
case "$ACTION" in
ifup|ifdown|ifupdate) /usr/libexec/ax50-wanled ;;
esac
