#!/bin/sh
# PPA: точки Wi-Fi и туннели WAN появляются позже /etc/init.d/ax50-ppa.
[ -e /var/run/ax50-ppa ] || exit 0
[ "$ACTION" = add ] || exit 0
case "$INTERFACE" in
wlan*|pppoe-*|l2tp-*) /usr/libexec/ax50-ppa register ;;
esac
exit 0
