#!/bin/sh
# PPA: туннели WAN (PPPoE, L2TP) появляются позже /etc/init.d/ax50-ppa.
[ -e /var/run/ax50-ppa ] || exit 0
[ "$ACTION" = add ] || exit 0
case "$INTERFACE" in
pppoe-*|l2tp-*) ppacmd addwan -i "$INTERFACE" >/dev/null 2>&1 ;;
esac
exit 0
