#!/bin/sh
# irqbalance разносит прерывания сети и Wi-Fi по всем 4 потокам процессора
uci -q get irqbalance.irqbalance >/dev/null || exit 0
uci -q set irqbalance.irqbalance.enabled=1
uci -q commit irqbalance
exit 0
